# Simple Voice Chat client config v1.20.1-2.5.29

# The scale of the player icons in the group chat HUD
group_hud_icon_scale=2.0
# The orientation of the player icons in the group chat HUD
# Valid values are 'VERTICAL' and 'HORIZONTAL'
group_player_icon_orientation=VERTICAL
# The X position of the player icons in the group chat HUD
# Negative values mean anchoring to the right instead
group_player_icon_pos_x=4
# The Y position of the player icons in the group chat HUD
# Negative values mean anchoring to the bottom instead
group_player_icon_pos_y=60
# How listening to other players should work when using freecam mods
# Valid values are 'CAMERA' and 'PLAYER'
# CAMERA: You will hear the voice chat around your camera. Whether you will still be able to hear the voice chat when the camera is far away from your character depends on the voice chat broadcast range of the server
# PLAYER: You will hear the voice chat around your character no matter where your camera is
freecam_mode=CAMERA
