name: Publish modpack

on:
  push:
    branches:
      - trunk
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Verify that mods.json is up to date
        env:
          CFCORE_API_TOKEN: ${{ secrets.CFCORE_API_TOKEN }}
        run: |
          nix run .#lockMods
          git diff --exit-code
      - name: Run `nix build`
        run: nix build -L --show-trace .
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: result/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
